# Example of a configuration

[server]
# To interact with the server API
endpoint = "http://10.0.0.1:8080"
secret = "supersegreto"

[database]
user = "user"
password = "password"
database = "sasso-router"
host = "localhost"
port = 5433

[network]
usable_subnet = "10.254.0.0/16"
new_subnet_prefix = 29

[gateway]
type = "proxmox"

[gateway.proxmox]
url = "https://localhost:8006"
insecure_skip_verify = true
token_id = "root@pam!mytokenid"
secret = "2630dda0-b730-4dc7-be14-0b3582c97224"
vmid = 9100
