name: Build and tests

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Checkout the repo
        uses: actions/checkout@v5

      - name: Install run-all
        run: npm i npm-run-all --save-dev

      - name: Install just
        run: sudo apt install just

      - name: Build application
        run: just build

      - name: Check formatting
        run: just check-format

      - name: Check lint
        run: just frontend-lint

